import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'react-toastify'
import Card from '@/components/common/Card'
import Button from '@/components/common/Button'
import StatusBadge from '@/components/common/StatusBadge'
import { getMockInspections } from '@/services/inspections'
import type { Inspection } from '@/types'

type StatusFilter = 'all' | 'completed' | 'processing' | 'failed'

export default function History() {
  const { t } = useTranslation()
  const [search, setSearch] = useState(() => localStorage.getItem('wtm_history_search') || '')
  const [statusFilter, setStatusFilter] = useState<StatusFilter>(() =>
    (localStorage.getItem('wtm_history_status') as StatusFilter) || 'all'
  )
  const [showFilter, setShowFilter] = useState(false)

  useEffect(() => {
    localStorage.setItem('wtm_history_search', search)
  }, [search])

  useEffect(() => {
    localStorage.setItem('wtm_history_status', statusFilter)
  }, [statusFilter])

  const inspections = getMockInspections()

  const filtered = inspections.filter((i) => {
    const matchesSearch = i.turbineId.toLowerCase().includes(search.toLowerCase())
    const matchesStatus = statusFilter === 'all' || i.status === statusFilter
    return matchesSearch && matchesStatus
  })

  const handleExport = () => {
    const isRu = t('history.title') === 'История инспекций'
    const labels = {
      title: isRu ? 'Отчёт об инспекциях' : 'Inspection Report',
      date: isRu ? 'Дата' : 'Date',
      turbine: isRu ? 'Турбина' : 'Turbine',
      defects: isRu ? 'Дефекты' : 'Defects',
      status: isRu ? 'Статус' : 'Status',
      footer: isRu ? 'Сгенерировано WTM' : 'Generated by WTM',
    }

    const rows = filtered.map(
      (i) => `<tr>
        <td style="padding:8px;border:1px solid #ddd">${i.date}</td>
        <td style="padding:8px;border:1px solid #ddd">${i.turbineId}</td>
        <td style="padding:8px;border:1px solid #ddd">${i.defects.length}</td>
        <td style="padding:8px;border:1px solid #ddd">${t(`history.statuses.${i.status}`)}</td>
      </tr>`
    ).join('')

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${labels.title}</title></head>
<body style="font-family:sans-serif;padding:20px">
  <h1 style="color:#2563eb">${labels.title}</h1>
  <table style="width:100%;border-collapse:collapse">
    <thead><tr style="background:#f3f4f6">
      <th style="padding:8px;border:1px solid #ddd;text-align:left">${labels.date}</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:left">${labels.turbine}</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:left">${labels.defects}</th>
      <th style="padding:8px;border:1px solid #ddd;text-align:left">${labels.status}</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <p style="color:#9ca3af;font-size:12px;margin-top:20px">${labels.footer}</p>
</body></html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'report.html'
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Report exported')
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{t('history.title')}</h1>
          <p className="text-gray-500 mt-1">{t('history.desc')}</p>
        </div>
        <Button variant="secondary" onClick={handleExport}>{t('history.export')}</Button>
      </div>

      <Card>
        <div className="flex items-center gap-3 pb-4 border-b border-gray-100 mb-4">
          <input
            type="text"
            placeholder={t('history.search')}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
          <div className="relative">
            <Button variant="secondary" size="sm" onClick={() => setShowFilter(!showFilter)}>
              {t('history.filter')}
            </Button>
            {showFilter && (
              <div className="absolute right-0 top-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg z-10 w-44">
                {(['all', 'completed', 'processing', 'failed'] as StatusFilter[]).map((s) => (
                  <button
                    key={s}
                    className={`block w-full text-left px-4 py-2 text-sm hover:bg-gray-50 ${
                      statusFilter === s ? 'bg-blue-50 text-blue-700 font-medium' : 'text-gray-700'
                    }`}
                    onClick={() => { setStatusFilter(s); setShowFilter(false) }}
                  >
                    {s === 'all' ? t('history.all') : t(`history.statuses.${s}`)}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-gray-500 border-b border-gray-100">
                <th className="pb-3 font-medium">{t('history.date')}</th>
                <th className="pb-3 font-medium">{t('history.turbine')}</th>
                <th className="pb-3 font-medium">{t('history.defects')}</th>
                <th className="pb-3 font-medium">{t('history.status')}</th>
                <th className="pb-3 font-medium">{t('history.actions')}</th>
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={5} className="text-center text-gray-400 py-8">{t('common.noData')}</td>
                </tr>
              ) : (
                filtered.map((inspection: Inspection) => (
                  <tr key={inspection.id} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="py-3 text-gray-900">{inspection.date}</td>
                    <td className="py-3 font-medium text-gray-900">{inspection.turbineId}</td>
                    <td className="py-3 text-gray-900">{inspection.defects.length}</td>
                    <td className="py-3"><StatusBadge status={inspection.status} /></td>
                    <td className="py-3">
                      <div className="flex gap-2">
                        <Button variant="ghost" size="sm">{t('history.view')}</Button>
                        <Button variant="ghost" size="sm" className="text-red-600 hover:text-red-700">
                          {t('history.delete')}
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  )
}
